#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/Steven/Desktop/CPSC 427/Assignments/A1_A3_student_template/cpsc-427-dev/template/"
